### PR TITLE
Update "Kieu nam features" for Tam1features

### PR DESCRIPTION
**Pull request by MinhTamLA**
Start to Update "Kieu nam features" for Tam1features

### CODE REVIEW

**Review by MinhTamSheenB — APPROVED** [review]

**Review by MinhTamSheenB — APPROVED** [review]
ok

**Comment by MinhTamSheenB** [comment]
ok

**Review by MinhTamSheenB — APPROVED** [review]
okkkk

**Review by MinhTamSheenB — APPROVED** [review]
okkk

**Comment by MinhTamLA** [comment]
ok

**Pull request closed without merging**
